stages:
  data_visualization:
    cmd: python src/data_visualization.py
    deps:
      - src/data_visualization.py
      - data/raw/datos_creditos.csv
      - data/raw/datos_tarjetas.csv
    outs:
      - reports/figures/target_distribution_falta_pago.png
      - reports/figures/creditos_objetivo_credito.png
      - reports/figures/creditos_situacion_vivienda.png
      - reports/figures/tarjetas_estado_civil.png
      - reports/figures/tarjetas_estado_cliente.png
      - reports/figures/tarjetas_genero.png
      - reports/figures/tarjetas_nivel_educativo.png
      - reports/figures/tarjetas_nivel_tarjeta.png
      - reports/figures/correlaciones_creditos.png
      - reports/figures/correlaciones_tarjetas.png
      - reports/figures/variable_economica_vs_mora.png
      - reports/figures/relacion_variables_economicas_mora.png

  test_pandera:
    cmd: pytest --html=test/report_pandera.html --self-contained-html tests/test_data_quality.py -v || exit 0
    deps:
      - data/raw/datos_creditos.csv
      - data/raw/datos_tarjetas.csv
      - tests/test_data_quality.py
    outs:
      - test/report_pandera.html

  test_ge:
    cmd: pytest --html=test/report_ge.html --self-contained-html tests/test_data_quality_ge.py -v || exit 0
    deps:
      - data/raw/datos_creditos.csv
      - data/raw/datos_tarjetas.csv
      - tests/test_data_quality_ge.py
    outs:
      - test/report_ge.html

  data_processing:
    cmd: python src/data_prep.py
    deps:
      - src/data_prep.py
      - data/raw/datos_creditos.csv
      - data/raw/datos_tarjetas.csv
    outs:
      - data/processed/datos_integrados.csv
   